In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_boston
boston_dataset = load_boston()


In [2]:
df_boston = pd.DataFrame(boston_dataset.data)
df_boston.columns = boston_dataset.feature_names

In [3]:
#append 'price' ,target,as a new column to dataset
df_boston['Price'] = boston_dataset.target
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  Price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [4]:
#assign features on X axis and Targets on Y axis
X_features = boston_dataset.data
Y_target =  boston_dataset.target

In [5]:
#import linear model - the estimator
from sklearn.linear_model import LinearRegression
lineReg = LinearRegression()

In [6]:
#fit data into estimator
lineReg.fit(X_features,Y_target)

LinearRegression()

In [7]:
#print the intercept
print('estimated intercept is %.2f' %lineReg.intercept_)

estimated intercept is 36.46


In [8]:
#print the coefficient
print('estimated coeff is %.2f' %len(lineReg.coef_))

estimated coeff is 13.00


In [9]:
#train them model by splitting the whole dataset into train and test datasets 75% and 25%
from sklearn.model_selection import train_test_split

#from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_features,Y_target,random_state = 0)

In [10]:
#print the dataset matrix
print(boston_dataset.data.shape)

(506, 13)


In [11]:
#print the shapes of training and testing datasets
print(X_train, X_test, Y_train, Y_test)

[[1.9133e-01 2.2000e+01 5.8600e+00 ... 1.9100e+01 3.8913e+02 1.8460e+01]
 [1.0328e-01 2.5000e+01 5.1300e+00 ... 1.9700e+01 3.9690e+02 9.2200e+00]
 [1.0469e-01 4.0000e+01 6.4100e+00 ... 1.7600e+01 3.8925e+02 6.0500e+00]
 ...
 [1.5098e-01 0.0000e+00 1.0010e+01 ... 1.7800e+01 3.9451e+02 1.0300e+01]
 [2.2927e-01 0.0000e+00 6.9100e+00 ... 1.7900e+01 3.9274e+02 1.8800e+01]
 [1.3914e-01 0.0000e+00 4.0500e+00 ... 1.6600e+01 3.9690e+02 1.4690e+01]] [[6.7240e-02 0.0000e+00 3.2400e+00 ... 1.6900e+01 3.7521e+02 7.3400e+00]
 [9.2323e+00 0.0000e+00 1.8100e+01 ... 2.0200e+01 3.6615e+02 9.5300e+00]
 [1.1425e-01 0.0000e+00 1.3890e+01 ... 1.6400e+01 3.9374e+02 1.0500e+01]
 ...
 [3.4940e-01 0.0000e+00 9.9000e+00 ... 1.8400e+01 3.9624e+02 9.9700e+00]
 [9.8490e-02 0.0000e+00 2.5650e+01 ... 1.9100e+01 3.7938e+02 1.7580e+01]
 [7.5030e-02 3.3000e+01 2.1800e+00 ... 1.8400e+01 3.9690e+02 6.4700e+00]] [18.5 19.6 33.2 13.1  7.5 13.6 17.4  8.4 35.4 24.  13.4 26.2  7.2 13.1
 24.5 37.2 25.  24.1 16.6 32.9 36.2 11.  

In [12]:
#fit the training sets into the model
lineReg.fit(X_train,Y_train)

LinearRegression()

In [13]:
#The mean square error
print('MSE value is%.2f'%np.mean((lineReg.predict(X_test)-Y_test)**2))

MSE value is29.78


In [14]:
#Calculate the variance
print('variance score is %.2f'%lineReg.score(X_test,Y_test))

variance score is 0.64
